name: Daily Stoic Quote

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Stoic Quote
        uses: benatsh/stoic-quote-action@v1.0.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}